# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true

        # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
        cookies: ['/^SS?ESS/', '/^wordpress_/', '/^wp-settings/', '/^wp-postpass_/']
    redirects:
      expires: 1d
      paths:
        '^/wp-admin$':
          to: "/wp/wp-admin/"
          regexp: true
        '^/wp-admin/(.*)':
          to: "/wp/wp-admin/$1"
          regexp: true
        '^/colby-impact$':
          to: '/darenorthward/'
          regexp: true
          code: 302
        '^/colby-impact/(.*)':
          to: '/darenorthward/'
          regexp: true
          code: 302
        # '^/give/?$': 
        #   to: 'https://www.givecampus.com/l2ttfj'   
        #   regexp: true
        #   code: 301
        '^/category/news/impact-stories/?$': 
          to: '/impact-stories'   
          regexp: true
          code: 301

# *ALL* www.* requests should be redirected back to primary domain
"https://www.{all}/":
    type: redirect
    to: "https://{default}/"
# All vanity domain requests should be redirected to primary domain
"https://{all}/":
  type: redirect
  to: "https://{default}/"
